services:
  nginx:
    container_name: ${APP_ID}_nginx
    build:
      context: ./docker/nginx
      args:
        - APP_ID=${APP_ID}
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www/html
  php:
    container_name: ${APP_ID}_php
    build:
      context: ./docker/php-fpm
    volumes:
      - ./:/var/www/html
  redis:
    container_name: ${APP_ID}_redis
    image: redis:7.4-alpine3.20
  mysql:
    container_name: ${APP_ID}_mysql
    image: mysql:8.4
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
