services:
  nginx:
    container_name: ${APP_ID}_nginx
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www/html
      - ./docker/nginx/app.conf:/etc/nginx/conf.d/app.conf
  php:
    container_name: ${APP_ID}_php
    image: php:8.3-fpm
    build:
      context: ./docker/php-fpm
    volumes:
      - ./:/var/www/html
  redis:
    container_name: ${APP_ID}_redis
    image: redis:7.4-alpine3.20
  mysql:
    container_name: ${APP_ID}_mysql
    image: mysql:8.4
